version: '3.8'

services:
  finance-dashboard:
    build: .
    ports:
      - "2345:2345"
    environment:
      - NODE_ENV=production
      - PORT=2345
    volumes:
      - uploads:/app/backend/uploads
      - ./backend/data:/app/backend/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2345/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
    driver: local