[build]
  base = "frontend/"
  publish = "build/"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "../backend/src/"