[build]
  base = "frontend/"
  publish = "build/"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  REACT_APP_API_URL = "https://fin2-4.onrender.com"

# Remove functions since we're using external Render backend
# [functions]
#   node_bundler = "esbuild"
#   external_node_modules = ["sqlite3", "mongodb"]

# Remove API redirects since backend is on Render
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/:splat"
#   status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200