# Render.com deployment configuration for Finance Dashboard
version: 2

services:
  # Full-stack Node.js service (serves both API and static files)
  - type: web
    name: finance-dashboard
    runtime: node
    region: ohio
    plan: starter
    buildCommand: cd backend && npm install && cd ../frontend && npm install && chmod +x node_modules/.bin/* && npm run build && cd ..
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY  
        generateValue: true
      - key: API_SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://rhasan:GlassDoor2025@cluster0.tj04exd.mongodb.net/genius_db?retryWrites=true&w=majority&appName=Cluster0